### ISSUE TITLE
Please change the syntax test file path to use the installed package's name "TOML"

### ISSUE THREAD

**Issue by FichteFoll** [jasonwilliams/sublime_toml_highlighting#10]
When running the All Syntaxes build system, this package generates a lot of failures because the specified syntax in the test file cannot be found at `Packages/sublime_toml_highlighting/TOML.sublime-syntax`. This is because the package is installed by PC as `TOML`. Please adjust this.

**Comment by writeml** [comment]
I'm so glad I found this issue, because now I know about [syntax definition tests](http://www.sublimetext.com/docs/3/syntax.html#testing) -- Thanks y'all!

**Comment by jasonwilliams** [comment]
fixed
