### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by chrissimpkins** [jasonwilliams/sublime_toml_highlighting#17]
Is there a license for this project?

**Comment by bjorn-ove** [comment]
It would be great if one could be added as without one it is effectively not allowed to use it. The problem now is that everyone that has commited to this repo would need to approve any license added. The default is that each line belongs to whoever commited it and can't be shared by anyone.

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

ref: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by jasonwilliams** [comment]
Thanks @BearOve ill look into it

**Comment by ghost** [comment]
MIT-licensed alternative re-created from scratch: https://github.com/sourcegraph/TOML-syntax-highlighting

maybe just adopt its codebase instead, going forward?

**Comment by jasonwilliams** [comment]
A license has been added
