### ISSUE TITLE
No syntax highlighting under ST4

### ISSUE THREAD

**Issue by anentropic** [jasonwilliams/sublime_toml_highlighting#18]
I recently upgraded to ST4 and installed this on a new machine, but there's no highlighting :(

I have v2.4.0 installed under ST3 on another laptop and it's working fine

**Comment by ehuss** [comment]
It should be working. Some things to check:
* Verify it is installed.
* Ensure it isn't disabled (`ignored_packages` in settings).
* If you had the TOML file open when you installed it, it won't automatically switch. You can run the command "Set Syntax: TOML" to switch (or click the syntax name in the bottom-right corner of the status bar).
* Check the console for any errors.

**Comment by anentropic** [comment]
- it's installed (v2.4.0)
- my `ignored_packages` looks like:
   ```	"ignored_packages":
	[
		"Vintage",
	],
   ```
- I have closed and re-opened the file and it shows as TOML syntax in the bottom-right
- no TOML errors in the console, and no new console logging when opening the .toml file

I've also closed and re-opened ST4

**Comment by ehuss** [comment]
Hm, sorry I don't have any other ideas. It has worked on all the systems I have tried with build 4107. You might try asking on the user forum or discord server.

**Comment by anentropic** [comment]
my mistake, it seems it had opened as "Plain Text (TOML)"

after setting "TOML" syntax it works
