### ISSUE TITLE
"inline-keyval-sep" context should be popped when encountering a closing brace

### ISSUE THREAD

**Issue by FichteFoll** [jasonwilliams/sublime_toml_highlighting#22]
With a line as follows (which can easily happen during typing):
```
aioprometheus = {extras = ["quart"], version = "^23.12.0", }
```
the next line of the file will basically always entirely be marked as `invalid.illegal`, which is not good DX.

The context should be popped on the unexpected `}`.

![2024-08-16_16-05-52](https://github.com/user-attachments/assets/c171941f-aca7-4833-beb7-ee66fe269673)

**Comment by ehuss** [comment]
Thanks for the report! I opened https://github.com/jasonwilliams/sublime_toml_highlighting/pull/23 with a fix for this specific situation. I'm not sure if it is the best way to handle it. The current structure is a bit convoluted, and it's a bit hard to pop out just the right amount of the stack.

I'll use that change for a while locally before merging just to see if there are any problems in day-to-day use on my end. Would appreciate if you could look at it, too.
