### ISSUE TITLE
Highlight section headers as entity.name.section

### ISSUE THREAD

**Issue by FichteFoll** [jasonwilliams/sublime_toml_highlighting#3]
^ title

`entity.other.attribute-name` is a hack and semantically means something different, which most color schemes respect.

`meta.tag.table` also means something different.

**Comment by jasonwilliams** [comment]
@FichteFoll to be honest the whole syntax file needs rewriting (into the new .sublime-syntax format). but thanks for these i will keep them in mind when i do that

**Comment by FichteFoll** [comment]
Yeah, that's fair enough. I was just using files with the TOML syntax and thought I might as well see if there's a package on PC. Unfortunately, it's very non-standard.

**Comment by FichteFoll** [comment]
Now highlighted as `entity.name.table` via https://github.com/jasonwilliams/sublime_toml_highlighting/commit/bfc0c459afacc99486d704540b2947e9353ed7e1.
