### ISSUE TITLE
Update to sublime-syntax

### ISSUE THREAD

**Issue by ehuss** [jasonwilliams/sublime_toml_highlighting#6]
I'd like to fix some of the bugs in the TOML highlighting, and before doing that I think it would be nice if this was updated to `sublime-syntax`, possibly updated to conform with Sublime 3's [scope naming rules](https://www.sublimetext.com/docs/3/scope_naming.html), and include syntax tests.

@Jayflux I'd be happy to work on these changes.  Would you be OK with a PR for this?

**Comment by jasonwilliams** [comment]
@ehuss  absolutely
I was going to do it myself but ive completely ran out of time lately.

Thanks for picking this up

**Comment by ehuss** [comment]
I hope it's the good kind of busy and not the annoying kind.

I just opened a PR with the changes.  No rush to look at it, of course.  I broke it up into separate commits to maybe make it easier to see the individual changes.  There are a lot of judgement calls for things like scope naming and how aggressive to be with error highlighting.  Feel free to send me whatever feedback or questions.
